version: "3.8"

services:
    nginx:
        container_name: nginx
        restart: always
        image: nginx:alpine
        ports:
            - "0.0.0.0:80:8000"
        volumes:
            - ./www:/var/www
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        container_name: php
        restart: always
        build:
            dockerfile: ./php-fpm/Dockerfile
            context: .
        environment:
            TZ: "Asia/Baku"
        ports:
            - "9000:9000"
        volumes:
            - ./www:/var/www

    mariadb:
        image: mariadb:10.8.2
        restart: always
        environment:
            MARIADB_USER: root
            MARIADB_PASSWORD: pass
            MARIADB_ROOT_PASSWORD: pass
            TZ: "Asia/Baku"
        volumes:
            - data_db:/var/lib/mysql
        ports:
            - "3306:3306"
        depends_on:
            - nginx

volumes:
    data_db: {}
