version: "3.8"

services:
    nginx:
        container_name: nginx
        restart: always
        image: nginx:alpine
        ports:
            - "8000:8000"
        volumes:
            - ./www:/var/www
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        container_name: php
        restart: always
        build:
            dockerfile: ./php-fpm/Dockerfile
            context: .
        ports:
            - "9000:9000"
        volumes:
            - ./www:/var/www

    mariadb:
        image: mariadb:10.8.2
        restart: always
        environment:
            MYSQL_DATABASE: wpdb
            MYSQL_USER: root
            MYSQL_PASSWORD: pass
            MYSQL_RANDOM_ROOT_PASSWORD: pass
        volumes:
            - data_db:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    data_db: {}
